version: "3.6"
services:

  openindoor-db:
    image: postgis/postgis:13-3.1
    volumes:
       - db-storage:/var/lib/postgresql/data
      #  - init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      POSTGRES_DB: openindoor-db
      POSTGRES_USER: openindoor-db-admin
      POSTGRES_PASSWORD: admin123
    # ports:
    # - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 19991:8080

  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   # volumes:
  #   #    - pgadmin:/root/.pgadmin
  #   ports:
  #     - 19091:80
  #   restart: unless-stopped

# volumes:
#   pgadmin:      
    
    
  tegola:
    image: gospatial/tegola:v0.13.0
    environment:
      POSTGRES_DB: openindoor-db
      POSTGRES_USER: openindoor-db-admin
      POSTGRES_PASSWORD: admin123    
    command: serve --config /opt/tegola_config/config.toml
    volumes:
    - ./tegola:/opt/tegola_config
    ports:
    - 8080:8080

  places-finder:
    # dns:
    # - 213.186.33.99
    build:
      context: places-finder
    image: openindoor/places-finder
    environment:
      POSTGRES_DB: openindoor-db
      POSTGRES_USER: openindoor-db-admin
      POSTGRES_PASSWORD: admin123
    command: /places-finder/places-finder.py
    volumes:
    # - pbf-storage:/data
    - ./places-finder/data:/data
    - ./places-finder/test.py:/places-finder/test.py
    - ./places-finder/places-finder.py:/places-finder/places-finder.py
    - ./places-finder/places-finder-relation.py:/places-finder/places-finder-relation.py
    - ./places-finder/indoor-miner.py:/places-finder/indoor-miner.py
    - ./places-finder/indoor-analyser.py:/places-finder/indoor-analyser.py
    - ./places-finder/requirements.txt:/places-finder/requirements.txt
    - ./places-finder/mygeojson.json:/places-finder/mygeojson.json
    - ./places-finder/regions.json:/places-finder/regions.json
    - ./test:/test

  indoor-miner:
    image: openindoor/places-finder
    environment:
      POSTGRES_DB: openindoor-db
      POSTGRES_USER: openindoor-db-admin
      POSTGRES_PASSWORD: admin123
    command: /places-finder/indoor-miner.py
    volumes:
    - ./places-finder/data:/data
    - ./places-finder/test.py:/places-finder/test.py
    - ./places-finder/indoor-miner.py:/places-finder/indoor-miner.py
    - ./places-finder/regions.json:/places-finder/regions.json

  #   # - ./places-flask.py:/places/places-flask.py
  #   # - ./ogr2ogr.py:/places/ogr2ogr.py
  #   # - ./init_db.sh:/places/init_db.sh
  #   # - ./import.sh:/places/import.sh
  #   # - ./test:/test
  #   # ports:
  #   #   - 8001:80
  #   command: /places-finder/places-finder.py

volumes:
  pbf-storage:
  db-storage: