[webserver]
port = ":8080"
hostname = "tegola.openindoor.io"
uri_prefix = ""

# register data providers
[[providers]]
name = "openindoor"           # provider name is referenced from map layers
type = "postgis"        # the type of data provider. currently only supports postgis
host = "openindoor-db"      # postgis database host
port = 5432             # postgis database port
database = "openindoor-db"       # postgis database name
user = "openindoor-db-admin"         # postgis database user
password = "admin123"           # postgis database password
srid = 4326             # The default srid for this provider. If not provided it will be WebMercator (3857)

  [[providers.layers]]
  name = "footprint"
  geometry_fieldname = "geometry"
  id_fieldname = "id"
  srid = 4326
  sql = """
      SELECT
          alt_name,
          amenity,
          architect,
          building,
          "building:height",
          "building:levels",
          "building:level",
          "building:max_level",
          "building:part",
          height,
          level,
          maxheight,
          min_height,
          min_level,
          max_level,
          maxheight,
          museum,
          name,
          region,
          tourism,
          shop,
          wheelchair,
          wikipedia,
          ('x'||substr(md5(id),1,16))::bit(64)::bigint as tegola_id,
          ST_AsBinary(geometry) AS geometry,
          ST_GeometryType(geometry) AS geometry_type
      FROM footprint
      WHERE geometry && !BBOX!
  """

  [[providers.layers]]
  name = "pins"
  geometry_fieldname = "centroid"
  id_fieldname = "id"
  srid = 4326
  sql = """
      SELECT
          ('x'||substr(md5(id),1,16))::bit(64)::bigint as tegola_id,
          ST_AsBinary(centroid) AS centroid,
          ST_GeometryType(centroid) AS centroid_type
      FROM footprint
      WHERE centroid && !BBOX!
  """

  [[providers.layers]]
  name = "indoor"
  geometry_fieldname = "geometry"
  id_fieldname = "id"
  srid = 4326
  sql = """
      SELECT
          "addr:housenumber",
          conveying,
          brand,
          "building:levels",
          cuisine,
          height,
          highway,
          indoor,
          level,
          "level:ref",
          name,
          operator,
          ref,
          region,
          shop,
          source,
          wikipedia,
          ('x'||substr(md5(id),1,16))::bit(64)::bigint as tegola_id,
          ST_AsBinary(geometry) AS geometry,
          ST_GeometryType(geometry) AS geometry_type
      FROM indoor
      WHERE geometry && !BBOX!
  """

[[maps]]
name = "openindoor"
#center = [-1.70223, 48.11947, 17.0]
center = [2.3579127, 48.8762027, 17.0]

  [[maps.layers]]
  provider_layer = "openindoor.footprint"
  min_zoom = 12
  max_zoom = 20

  [[maps.layers]]
  provider_layer = "openindoor.pins"
  min_zoom = 4
  max_zoom = 12

  [[maps.layers]]
  provider_layer = "openindoor.indoor"
  min_zoom = 15
  max_zoom = 20
